### ISSUE TITLE
Browser Caching Issues In Edge

### ISSUE THREAD

**Issue by hunterwilliams** [marklogic/slush-marklogic-node#110]
As a user, I'd like to get be able to get new data/login properly when using a Microsoft browser (Edge tested - IE likely affected as well). 

@daveegrant asked for help to check out a possible issue and working him found that browser cache seems to be an issue

See this: http://stackoverflow.com/questions/16971831/better-way-to-prevent-ie-cache-in-angularjs

Recreation:

Start server
Windows 10 Edge Browser - Login slush generated app. Logout
Stop server
Windows 10 Edge Browser- Login again. It works with the server off. See network logs. Reads something like

``
Name	Protocol	Method	Result	Content type	Received	Time	Initiator
http://your-server-here.com:8001/user/login?password=password&username=user	HTTP	GET	200	application/json	(from cache)	0 s	
``

**Comment by daveegrant** [comment]
An alternate to the suggestion in the linked article is to add a noCache function that adds the response headers to prevent caching.  That function can be invoked in the proxy function and any other function where it makes sense (e.g. - /user/login).  The advantage of this approach is that requests for static resources will not include the no-cache response headers since it makes sense for them to be cached.

**Comment by grtjn** [comment]
+1 for adding no-cache response header to POST/PUT/DELETE in middle-tier..

**Comment by hunterwilliams** [comment]
So should we go ahead and do this on all calls? Or just some? 
Also I'm not sure if a combined js file is created with a hash each change or not - I know that's an option that some node projects use.

**Comment by grtjn** [comment]
In middle-tier for any dynamic POST/PUT/DELETE (the login is a dynamic call). The hash is more about the static files, but could be useful as well.

**Comment by hunterwilliams** [comment]
@daveegrant Can you verify I did this correctly? See #158
