### ISSUE TITLE
included init scripts and forever.js not working

### ISSUE THREAD

**Issue by joemfb** [marklogic/slush-marklogic-node#269]
Specifically stop/restart doesn't actually kill the app, or remove the PID file. I've needed to manually kill the app and forever.js as well as remove the PID file to restart. I'll add more details when I can.

**Comment by patrickmcelwee** [comment]
Here's how to kill one of these zombie apps (as a workaround) ... thanks to @joemfb, @grtjn , Ryan Semerau for the details ...

1. Find the forever id corresponding to your app: `sudo forever list | grep <app-name>` ... The id is a 4-character hash
2. Kill that forever process with `sudo forever stop <forever-id>`

For me, that was enough to bring the app now. You might have to kill your app, if so, find the pid with `ps aux | grep <app-name>` and then `sudo kill <pid>. Worst come to worst, you might have to `sudo kill -9 <pid>` to bring it down.

**Comment by grtjn** [comment]
If using kill, make sure to kill both the node ui process, as well as its parent process if that is a forever monitor. The service .pid file will also remain behind, causing service start to complain. If it refuses, then use stop/start or restart. The stop command will flush the pid file..

**Comment by grtjn** [comment]
This issue has been bugging me for ages. It looks like the script options are messing things up, it used to work in the past. I found a good suggestion on internet though, you can specify your own uid, making forever stop failsafe. Just add this param to the forever start command: ` --uid=$NAME `, and then you can do forever stop on $NAME instead of $SCRIPT_NAME. Works like a charm..
