### ISSUE TITLE
Shouldn't setSnippet use superCtrl apply?

### ISSUE THREAD

**Issue by grtjn** [marklogic/slush-marklogic-node#280]
search.controller.js now has a setSnippet that calls `ctrl.search();`, but shouldn't it call `superCtrl.search.apply(ctrl, arguments);` instead? Not quite sure I understand the diff, but it seems to make sure superCtrl properties get set properly..

**Comment by joemfb** [comment]
Accidental closure ...

No, there's no need to reference the `superCtrl`. That's only needed to override an inherited ctrl method and extend instead of replace its behavior.

In other words, `ctrl.search()` IS `superCtrl.search()`, unless `ctrl.search()` has been overridden. If it has been overridden, then you want it, and not the base implementation ...

**Comment by grtjn** [comment]
Clear, thnx..
